#ifndef __MATLS_H__
#define __MATLS_H__

#include <openssl/sha.h>

#define GROUP_ID_LENGTH 2
#define TYPE_LENGTH 1
#define META_LENGTH 2
#define NUM_OF_KEYS_INFO 1

#define TYPE_DUMMY 0
#define TYPE_SERVER 1
#define TYPE_CLIENT 1
#define TYPE_CLIENT_SIDE 1
#define TYPE_SERVER_SIDE 2
#define TYPE_CLIENT_SIDE_WITH_SCT 3
#define TYPE_SERVER_SIDE_WITH_SCT 4

#define TLS_MD_ID_SIZE 32
#define TLS_MD_HASH_SIZE 32
#define TLS_MD_HMAC_SIZE 32

#define SSL_MAX_ACCOUNTABILITY_KEY_LENGTH 32
#define SSL_MAX_GLOBAL_MAX_KEY_LENGTH 32

#define SSL_CURVE_SECP256R1 23
#define SECP256r1_PUBKEY_LENGTH 64
#define SECRET_LENGTH 32
#define CLIENT 0
#define SERVER 1

#define MATLS_VERSION_LENGTH 2
#define MATLS_CIPHERSUITE_LENGTH 2
#define MATLS_HASH_OF_MASTER_SECRET_LENGTH SHA256_DIGEST_LENGTH
#define MATLS_TRANSCRIPT_LENGTH s->s3->tmp.finish_md_len

#define MATLS_P_LENGTH \
  (MATLS_VERSION_LENGTH + MATLS_CIPHERSUITE_LENGTH \
   + MATLS_HASH_OF_MASTER_SECRET_LENGTH + MATLS_TRANSCRIPT_LENGTH)

#define MATLS_P_PAIR_LENGTH \
  (MATLS_VERSION_LENGTH + MATLS_CIPHERSUITE_LENGTH \
   + MATLS_HASH_OF_MASTER_SECRET_LENGTH + s->pair->s3->tmp.finish_md_len)

#define MATLS_H_LENGTH 32

int idx;
extern int lock;

#endif /* __MATLS_H__ */
